Feature lesson10
dymont78/SauceDemo pull request #2
Opened 2021-05-25 09:35 UTC by dymont78

Внес изменения для Chain of ivocations, только не заработал тест LoginFactoryTect  по этому паттерну.

2021-05-26 19:38 UTC, vchesnakoutest requested changes
please make fixes

2021-05-26 19:38 UTC, vchesnakoutest commented on src/test/java/tests/LoginTest.java
> +                .loginFactory("standart_user", "secret_sauce");
в тестах обязательно должен быть Assert (проверь также остальные тесты)

2021-05-27 07:12 UTC, dymont78 commented on src/test/java/tests/LoginTest.java
> +                .loginFactory("standart_user", "secret_sauce");
Все исправил

2021-05-28 19:28 UTC, vchesnakoutest approved these changes
please fix variable name and merge

2021-05-28 19:28 UTC, vchesnakoutest commented on src/test/java/tests/ProductsTest.java
> +        String valueQTY = cartPage.getProductQty("Sauce Labs Bolt T-Shirt");
valueQty

2021-05-29 11:34 UTC, merged