Feature lesson12
dymont78/SauceDemo pull request #3
Opened 2021-05-27 13:05 UTC by dymont78

2021-05-28 19:33 UTC, vchesnakoutest requested changes
please make fixes and send to review again

2021-05-28 19:33 UTC, vchesnakoutest commented on pom.xml
> +            <version>7.4.0</version>
это тоже надо вынести в property

2021-05-28 19:33 UTC, vchesnakoutest commented on readme2.md
> +!!! Если версии зависимостей указаны через переменные в разделе <properties>, то зависимости не обновляются
да, все верно, скрипт в этом случае не работает.

2021-05-28 19:33 UTC, vchesnakoutest commented on src/main/java/constants/IConstants.java
> +    String CART_URL = "https://www.saucedemo.com/cart.html";
лучше домен вынести в отдельную константу, а потом уже делать конкатенацию:
 String SAUCE_DEMO_URL = "https://www.saucedemo.com"
 String CART_URL = SAUCE_DEMO_URL + "/cart.html";

2021-05-28 19:33 UTC, vchesnakoutest commented on src/test/java/tests/LoginTest.java
> +        //driver.findElement("//button[contains(.,'Add')]");
лучше закоменченый код либо удаляй, либо оставляй комментарий для чего он тут

2021-05-29 13:01 UTC, dymont78 commented on src/test/java/tests/LoginTest.java
> +        //driver.findElement("//button[contains(.,'Add')]");
Это со старой ветки, в мастере уже чистый код

2021-05-29 13:02 UTC, dymont78 commented on src/main/java/constants/IConstants.java
> +    String CART_URL = "https://www.saucedemo.com/cart.html";
Исправил

2021-05-29 13:02 UTC, dymont78 commented on pom.xml
> +            <version>7.4.0</version>
Исправил

2021-05-31 19:36 UTC, vchesnakoutest approved these changes

2021-05-31 20:59 UTC, merged